### ISSUE TITLE
static express has issues ....

### ISSUE THREAD

**Issue by DeepDiver1975** [kataras/server-benchmarks#3]
No matter if executed locally or via the docker image: it seems that the static express tests are failing ...

Any idea on this .....

THX a lot

```
➭ docker run -v ${PWD}:/data kataras/server-benchmarks
Running through docker container...[/go/src/server-benchmarks/_code/static/express]
$ npm install
$ node .
$ bombardier -c 125 -n 1000000 -t 2s -m GET --format=json --print=result http://localhost:5000
2020/05/20 09:19:36 Static:expressjs/express errors: dial tcp 127.0.0.1:5000: connect: connection refused

**Comment by ChipCE** [comment]
I have the same problem. I think the problem is not because express, other test also return <code>dial tcp [::1]:5000: connect: connection refused</code>

Replace <code>localhost</code> with ip address in <code>tests.yml</code> will fix that problem (for the first static test). I cannot get any other test to run, they all return 404 Not Found codes.

**Comment by kataras** [comment]
@DeepDiver1975  I've just re-run them, with clean node modules and upgrading nodejs to latest `v14.4.0`. I don't see these errors (Windows 10 1909, locally and docker image), but I am sure they are network-relative, as  @ChipCE recommended try to expose or change the address inside the `tests.yml`.  Could you please tell us the host OS? Linux, BSD or Darwin?

**Comment by DeepDiver1975** [comment]
THX

**Comment by HymanZHAN** [comment]
Still having this issue on Linux systems. Neither Fedora 33 nor PopOS (basically Ubuntu) 20.10 works. Win10 works, but WSL2 (Ubuntu 20.04) doesn't.

**Comment by HymanZHAN** [comment]
~Ah, some quick tinkering helped reveal the issue... I upgraded from go 1.15.2/1.15.3 to 1.15.6 and the problem is now gone.~
NVM, the problem still exists. And I noticed that a Go process remained running on port 5000 even after the test was terminated on error.
